# Uncomment this line to define a global platform for your project
platform :osx, '10.11'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Notifications_MacOS' do

  pod 'NWPusher', '~> 0.7.0'
  pod 'AWSCore', :path => "LocalPods/AWS-SDK-MacOS-port"
  pod 'AWSCognito', :path => "LocalPods/AWS-SDK-MacOS-port"
  pod 'AWSDynamoDB', :path => "LocalPods/AWS-SDK-MacOS-port"
  pod 'AWSS3', :path => "LocalPods/AWS-SDK-MacOS-port"

end